# @host = 03-pokedex-production-3ab7.up.railway.app
@host = localhost:3000


###  get all
GET http://{{host}}/products?limit=1&offset=1\
###
GET http://{{host}}/products?limit=100

###  get by id
GET http://{{host}}/products/Shirt ac'milan7

###  delete by id
DELETE  http://{{host}}/products/bc38b27a-129f-47f9-a64f-941c2ca4d6dd

###  post
POST http://{{host}}/products
content-type: application/json

{
    "title": "shirt ac'milan10",
    "sizes": ["SM", "M", "L", "XT"],
    "gender": "men",
    "price": 16.82

}

###  update
PATCH  http://{{host}}/products/027a0412-72db-44f0-bc18-d8c09548a94c
content-type: application/json

{

  "tags": [1,2]
}

###
GET https://pokeapi.co/api/v2/ability/1