# @host = 03-pokedex-production-3ab7.up.railway.app
@host = localhost:3000


###  get all
GET http://{{host}}/products?limit=1&offset=2
###
GET http://{{host}}/products?limit=100

###  get by term
GET http://{{host}}/products/f555d376-e844-41de-ab40-b6efec541ad8


###  create product
POST http://{{host}}/products
content-type: application/json

{
    "title": "shirt ac'milan17",
    "sizes": ["SM", "M", "L", "XT"],
    "gender": "men",
    "price": 16.82,
    "images":["http://image1.jpg", "http://image2.jpg"]

}

###  update
PATCH  http://{{host}}/products/027a0412-72db-44f0-bc18-d8c09548a94c
content-type: application/json

{
  "images": [ "http://image3.jpg"],
  "tags": ["1"]
}

###  delete by id
DELETE  http://{{host}}/products/f555d376-e844-41de-ab40-b6efec541ad8

### SEED

GET http://{{host}}/seed