# @host = 03-pokedex-production-3ab7.up.railway.app
@host = localhost:3000

### create user
POST http://{{host}}/api/auth/register
content-type: application/json

{
   "email": "htipantuna12@gmail.com",
   "password": "Axbycz321",
   "fullName": "henry Gustav"
}


### login user
POST http://{{host}}/api/auth/login
content-type: application/json

{
   "email": "test1@gmail.com",
   "password": "Axbycz321"
}


### test private 
GET http://{{host}}/api/auth/private
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijk1YmZjMjU1LWFiOTUtNDRjNC04NjFmLWRkNDg1YTZmMTc4NSIsImlhdCI6MTcyODA1MTg2NiwiZXhwIjoxNzI4MDU5MDY2fQ.KZodr3YIMlM-AM7AvElMLsts82VricwKyGQkWGWLfJ0

### test private2 
GET http://{{host}}/api/auth/private2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijk1YmZjMjU1LWFiOTUtNDRjNC04NjFmLWRkNDg1YTZmMTc4NSIsImlhdCI6MTcyODE2MTQ1NiwiZXhwIjoxNzI4MTY4NjU2fQ.Eq9YF20SOCbNmp1I42685D7Mzgvec47g0hIvo5umQnQ

### test private3
GET http://{{host}}/api/auth/private3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijk1YmZjMjU1LWFiOTUtNDRjNC04NjFmLWRkNDg1YTZmMTc4NSIsImlhdCI6MTcyODE2NzIwMCwiZXhwIjoxNzI4MTc0NDAwfQ.U25ysUfSxZpc77Y1XsTfTvtNPGLf_sqw1TrbVsFDmeM

### check auth status
GET http://{{host}}/api/auth/check-auth-status
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijg5NzY0NmMzLTY1YjAtNGU3MC1iYzRjLTQwNDVhM2QyYzViNyIsImlhdCI6MTcyODM0MDcyOCwiZXhwIjoxNzI4MzQ3OTI4fQ.vQCeOeFyWZ9uXi0wHy09yxlDOTQoOPuiGv9X2W_6E8g